This commit was manufactured by cvs2git to create tag 'STABLE'.
Sprout from master 2001-03-17 04:25:54 UTC kloczek <kloczek@pld-linux.org> '- patch from rawhide.'
Cherrypick from master 2003-02-13 10:09:32 UTC Artur Frysiak <artur@frysiak.net> 'do not use $1 in comment lines':
    autoconf-AC_EGREP.patch -> 1.1
    autoconf-info.patch -> 1.13
    autoconf-mawk.patch -> 1.5
    autoconf-version.patch -> 1.3
Cherrypick from master 2002-07-28 17:53:50 UTC kloczek <kloczek@pld-linux.org> '- merge DEVEL branch.':
    autoconf-fhs.patch -> 1.4
Cherrypick from RA-branch 2003-07-18 10:41:01 UTC Paweł Gołaszewski <blues@pld-linux.org> '- BR for RA. tnx qboosh for hint.':
    autoconf.spec -> 1.88.2.1

diff --git a/autoconf-mawk.patch b/autoconf-mawk.patch
--- a/autoconf-mawk.patch
+++ b/autoconf-mawk.patch
@@ -1,44 +1,41 @@
-diff -Naur autoconf-2.13/acspecific.m4 autoconf-2.13-p/acspecific.m4
---- autoconf-2.13/acspecific.m4	Tue Jan  5 14:27:52 1999
-+++ autoconf-2.13-p/acspecific.m4	Mon Jul  3 01:00:39 2000
-@@ -479,9 +479,9 @@
- AC_DEFUN(AC_PROG_RANLIB,
- [AC_CHECK_PROG(RANLIB, ranlib, ranlib, :)])
+diff -Nur autoconf-2.53.orig/configure autoconf-2.53/configure
+--- autoconf-2.53.orig/configure	Fri Mar  8 14:09:59 2002
++++ autoconf-2.53/configure	Sat Mar 16 13:12:23 2002
+@@ -1312,7 +1312,7 @@
+ echo "$as_me: WARNING: \`missing' script is too old or missing" >&2;}
+ fi
  
--dnl Check for mawk first since it's generally faster.
-+dnl Check for awk first since it's generally the one we would like to use :)
- AC_DEFUN(AC_PROG_AWK,
--[AC_CHECK_PROGS(AWK, mawk gawk nawk awk, )])
-+[AC_CHECK_PROGS(AWK, awk mawk gawk nawk, )])
- 
- AC_DEFUN(AC_PROG_YACC,
- [AC_CHECK_PROGS(YACC, 'bison -y' byacc, yacc)])
-diff -Naur autoconf-2.13/autoconf.texi autoconf-2.13-p/autoconf.texi
---- autoconf-2.13/autoconf.texi	Mon Jul  3 00:57:52 2000
-+++ autoconf-2.13-p/autoconf.texi	Mon Jul  3 01:03:19 2000
-@@ -1537,10 +1537,10 @@
+-for ac_prog in gawk mawk nawk awk
++for ac_prog in awk mawk gawk nawk
+ do
+   # Extract the first word of "$ac_prog", so it can be a program name with args.
+ set dummy $ac_prog; ac_word=$2
+diff -Nur autoconf-2.53.orig/doc/autoconf.texi autoconf-2.53/doc/autoconf.texi
+--- autoconf-2.53.orig/doc/autoconf.texi	Sat Mar 16 13:07:31 2002
++++ autoconf-2.53/doc/autoconf.texi	Sat Mar 16 13:09:40 2002
+@@ -3012,10 +3012,10 @@
  @defmac AC_PROG_AWK
- @maindex PROG_AWK
+ @acindex PROG_AWK
  @ovindex AWK
--Check for @code{mawk}, @code{gawk}, @code{nawk}, and @code{awk}, in that
+-Check for @code{gawk}, @code{mawk}, @code{nawk}, and @code{awk}, in that
 +Check for @code{awk}, @code{mawk}, @code{gawk}, and @code{nawk}, in that
- order, and set output variable @code{AWK} to the first one that it
--finds.  It tries @code{mawk} first because that is reported to be the
--fastest implementation.
-+finds.  It tries @code{awk} first because that is reported to be the
+ order, and set output variable @code{AWK} to the first one that is found.
+-It tries @code{gawk} first because that is reported to be the
+-best implementation.
++It tries @code{awk} first because that is reported to be the
 +implementation that our system usually runs.
  @end defmac
  
- @defmac AC_PROG_CC
-diff -Naur autoconf-2.13/configure autoconf-2.13-p/configure
---- autoconf-2.13/configure	Tue Jan  5 14:28:57 1999
-+++ autoconf-2.13-p/configure	Mon Jul  3 00:59:42 2000
-@@ -583,7 +583,7 @@
- done
- test -n "$M4" || M4="m4"
  
--for ac_prog in mawk gawk nawk awk
-+for ac_prog in awk
- do
- # Extract the first word of "$ac_prog", so it can be a program name with args.
- set dummy $ac_prog; ac_word=$2
+diff -Nur autoconf-2.53.orig/lib/autoconf/programs.m4 autoconf-2.53/lib/autoconf/programs.m4
+--- autoconf-2.53.orig/lib/autoconf/programs.m4	Mon Mar  4 15:34:20 2002
++++ autoconf-2.53/lib/autoconf/programs.m4	Sat Mar 16 13:11:53 2002
+@@ -258,7 +258,7 @@
+ 
+ # Check for gawk first since it's generally better.
+ AC_DEFUN([AC_PROG_AWK],
+-[AC_CHECK_PROGS(AWK, gawk mawk nawk awk, )])
++[AC_CHECK_PROGS(AWK, awk mawk gawk nawk, )])
+ 
+ 
+ # AC_PROG_INSTALL
