- merge DEVEL branch.
Changed files:
    autoconf-fhs.patch -> 1.4
    autoconf-info.patch -> 1.7
    autoconf-mawk.patch -> 1.5

diff --git a/autoconf-mawk.patch b/autoconf-mawk.patch
--- a/autoconf-mawk.patch
+++ b/autoconf-mawk.patch
@@ -1,41 +1,41 @@
---- autoconf-2.50c/doc/autoconf.texi.wiget	Sat Jul 14 18:10:11 2001
-+++ autoconf-2.50c/doc/autoconf.texi	Mon Jul 16 13:53:46 2001
-@@ -2883,10 +2883,10 @@
+diff -Nur autoconf-2.53.orig/configure autoconf-2.53/configure
+--- autoconf-2.53.orig/configure	Fri Mar  8 14:09:59 2002
++++ autoconf-2.53/configure	Sat Mar 16 13:12:23 2002
+@@ -1312,7 +1312,7 @@
+ echo "$as_me: WARNING: \`missing' script is too old or missing" >&2;}
+ fi
+ 
+-for ac_prog in gawk mawk nawk awk
++for ac_prog in awk mawk gawk nawk
+ do
+   # Extract the first word of "$ac_prog", so it can be a program name with args.
+ set dummy $ac_prog; ac_word=$2
+diff -Nur autoconf-2.53.orig/doc/autoconf.texi autoconf-2.53/doc/autoconf.texi
+--- autoconf-2.53.orig/doc/autoconf.texi	Sat Mar 16 13:07:31 2002
++++ autoconf-2.53/doc/autoconf.texi	Sat Mar 16 13:09:40 2002
+@@ -3012,10 +3012,10 @@
  @defmac AC_PROG_AWK
- @maindex PROG_AWK
+ @acindex PROG_AWK
  @ovindex AWK
--Check for @code{mawk}, @code{gawk}, @code{nawk}, and @code{awk}, in that
+-Check for @code{gawk}, @code{mawk}, @code{nawk}, and @code{awk}, in that
 +Check for @code{awk}, @code{mawk}, @code{gawk}, and @code{nawk}, in that
  order, and set output variable @code{AWK} to the first one that is found.
--It tries @code{mawk} first because that is reported to be the
--fastest implementation.
+-It tries @code{gawk} first because that is reported to be the
+-best implementation.
 +It tries @code{awk} first because that is reported to be the
 +implementation that our system usually runs.
  @end defmac
  
  
---- autoconf-2.50c/acspecific.m4.wiget	Fri Jun 15 19:46:01 2001
-+++ autoconf-2.50c/acspecific.m4	Mon Jul 16 13:53:46 2001
-@@ -113,9 +113,9 @@
- [AC_CHECK_TOOL(RANLIB, ranlib, :)])
+diff -Nur autoconf-2.53.orig/lib/autoconf/programs.m4 autoconf-2.53/lib/autoconf/programs.m4
+--- autoconf-2.53.orig/lib/autoconf/programs.m4	Mon Mar  4 15:34:20 2002
++++ autoconf-2.53/lib/autoconf/programs.m4	Sat Mar 16 13:11:53 2002
+@@ -258,7 +258,7 @@
  
- 
--# Check for mawk first since it's generally faster.
-+# Check for awk first since it's generally the one we would like to use :)
+ # Check for gawk first since it's generally better.
  AC_DEFUN([AC_PROG_AWK],
--[AC_CHECK_PROGS(AWK, mawk gawk nawk awk, )])
+-[AC_CHECK_PROGS(AWK, gawk mawk nawk awk, )])
 +[AC_CHECK_PROGS(AWK, awk mawk gawk nawk, )])
  
  
- # AC_PROG_YACC
---- autoconf-2.50c/configure.wiget	Thu Jul 12 14:46:00 2001
-+++ autoconf-2.50c/configure	Mon Jul 16 13:55:40 2001
-@@ -1215,7 +1215,7 @@
- # a AC-SUBST inside AC-PROG-GNU-M4.  Grmph!
- 
- # `autoconf' and `ifnames' use AWK.  And we need decent RE support.
--for ac_prog in mawk gawk nawk awk
-+for ac_prog in awk mawk gawk nawk
- do
-   # Extract the first word of "$ac_prog", so it can be a program name with args.
- set dummy $ac_prog; ac_word=$2
+ # AC_PROG_INSTALL
